//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTLWB.MTService.TranslationServiceLoc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TranslationRequest", Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    [System.SerializableAttribute()]
    internal partial class TranslationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private MTLWB.MTService.TranslationServiceLoc.ArrayOfString TextsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MTLWB.MTService.TranslationServiceLoc.LanguagePair LangPairField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransformIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomainIDField;
        
        private MTLWB.MTService.TranslationServiceLoc.ArrayOfString1 CustomizationIDsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassportIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MTLWB.MTService.TranslationServiceLoc.RequestOptionMask RequestOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReservedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal MTLWB.MTService.TranslationServiceLoc.ArrayOfString Texts {
            get {
                return this.TextsField;
            }
            set {
                if ((object.ReferenceEquals(this.TextsField, value) != true)) {
                    this.TextsField = value;
                    this.RaisePropertyChanged("Texts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        internal MTLWB.MTService.TranslationServiceLoc.LanguagePair LangPair {
            get {
                return this.LangPairField;
            }
            set {
                if ((object.ReferenceEquals(this.LangPairField, value) != true)) {
                    this.LangPairField = value;
                    this.RaisePropertyChanged("LangPair");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        internal string AppID {
            get {
                return this.AppIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AppIDField, value) != true)) {
                    this.AppIDField = value;
                    this.RaisePropertyChanged("AppID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        internal string TransformID {
            get {
                return this.TransformIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TransformIDField, value) != true)) {
                    this.TransformIDField = value;
                    this.RaisePropertyChanged("TransformID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        internal string DomainID {
            get {
                return this.DomainIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DomainIDField, value) != true)) {
                    this.DomainIDField = value;
                    this.RaisePropertyChanged("DomainID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        internal MTLWB.MTService.TranslationServiceLoc.ArrayOfString1 CustomizationIDs {
            get {
                return this.CustomizationIDsField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomizationIDsField, value) != true)) {
                    this.CustomizationIDsField = value;
                    this.RaisePropertyChanged("CustomizationIDs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        internal string PassportID {
            get {
                return this.PassportIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PassportIDField, value) != true)) {
                    this.PassportIDField = value;
                    this.RaisePropertyChanged("PassportID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        internal string ProviderID {
            get {
                return this.ProviderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderIDField, value) != true)) {
                    this.ProviderIDField = value;
                    this.RaisePropertyChanged("ProviderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        internal MTLWB.MTService.TranslationServiceLoc.RequestOptionMask RequestOptions {
            get {
                return this.RequestOptionsField;
            }
            set {
                if ((this.RequestOptionsField.Equals(value) != true)) {
                    this.RequestOptionsField = value;
                    this.RaisePropertyChanged("RequestOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        internal int Reserved {
            get {
                return this.ReservedField;
            }
            set {
                if ((this.ReservedField.Equals(value) != true)) {
                    this.ReservedField = value;
                    this.RaisePropertyChanged("Reserved");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LanguagePair", Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    [System.SerializableAttribute()]
    internal partial class LanguagePair : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetLanguageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string SourceLanguage {
            get {
                return this.SourceLanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceLanguageField, value) != true)) {
                    this.SourceLanguageField = value;
                    this.RaisePropertyChanged("SourceLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string TargetLanguage {
            get {
                return this.TargetLanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetLanguageField, value) != true)) {
                    this.TargetLanguageField = value;
                    this.RaisePropertyChanged("TargetLanguage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex", ItemName="string")]
    [System.SerializableAttribute()]
    internal class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", ItemName="string")]
    [System.SerializableAttribute()]
    internal class ArrayOfString1 : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestOptionMask", Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    internal enum RequestOptionMask : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CacheOnly = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoCache = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConfidenceScoreRequired = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TranslationResponse", Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    [System.SerializableAttribute()]
    internal partial class TranslationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MTLWB.MTService.TranslationServiceLoc.TItem[] TranslationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal MTLWB.MTService.TranslationServiceLoc.TItem[] Translations {
            get {
                return this.TranslationsField;
            }
            set {
                if ((object.ReferenceEquals(this.TranslationsField, value) != true)) {
                    this.TranslationsField = value;
                    this.RaisePropertyChanged("Translations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        internal string ProviderID {
            get {
                return this.ProviderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderIDField, value) != true)) {
                    this.ProviderIDField = value;
                    this.RaisePropertyChanged("ProviderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        internal int Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TItem", Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    [System.SerializableAttribute()]
    internal partial class TItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        internal int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        internal int Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TranslationSystemRequest", Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    [System.SerializableAttribute()]
    internal partial class TranslationSystemRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MTLWB.MTService.TranslationServiceLoc.LanguagePair LangPairFilterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionLanguageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string AppID {
            get {
                return this.AppIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AppIDField, value) != true)) {
                    this.AppIDField = value;
                    this.RaisePropertyChanged("AppID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal MTLWB.MTService.TranslationServiceLoc.LanguagePair LangPairFilter {
            get {
                return this.LangPairFilterField;
            }
            set {
                if ((object.ReferenceEquals(this.LangPairFilterField, value) != true)) {
                    this.LangPairFilterField = value;
                    this.RaisePropertyChanged("LangPairFilter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        internal string DescriptionLanguage {
            get {
                return this.DescriptionLanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionLanguageField, value) != true)) {
                    this.DescriptionLanguageField = value;
                    this.RaisePropertyChanged("DescriptionLanguage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TranslationSystemResponse", Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    [System.SerializableAttribute()]
    internal partial class TranslationSystemResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MTLWB.MTService.TranslationServiceLoc.TSItem[] TranslationSystemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal MTLWB.MTService.TranslationServiceLoc.TSItem[] TranslationSystems {
            get {
                return this.TranslationSystemsField;
            }
            set {
                if ((object.ReferenceEquals(this.TranslationSystemsField, value) != true)) {
                    this.TranslationSystemsField = value;
                    this.RaisePropertyChanged("TranslationSystems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TSItem", Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    [System.SerializableAttribute()]
    internal partial class TSItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MTLWB.MTService.TranslationServiceLoc.LanguagePair LangPairField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal MTLWB.MTService.TranslationServiceLoc.LanguagePair LangPair {
            get {
                return this.LangPairField;
            }
            set {
                if ((object.ReferenceEquals(this.LangPairField, value) != true)) {
                    this.LangPairField = value;
                    this.RaisePropertyChanged("LangPair");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        internal string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorRequest", Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    [System.SerializableAttribute()]
    internal partial class ErrorRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorResponse", Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    [System.SerializableAttribute()]
    internal partial class ErrorResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string ErrorString {
            get {
                return this.ErrorStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorStringField, value) != true)) {
                    this.ErrorStringField = value;
                    this.RaisePropertyChanged("ErrorString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex", ConfigurationName="TranslationServiceLoc.ITranslationServiceContract")]
    internal interface ITranslationServiceContract {
        
        // CODEGEN: Generating message contract since element name Request from namespace http://schemas.microsoft.com/MSNSearch/2005/09/fex is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/MSNSearch/2005/09/fex/Translate", ReplyAction="http://schemas.microsoft.com/MSNSearch/2005/09/fex/TranslateResponse")]
        MTLWB.MTService.TranslationServiceLoc.TranslateResponse Translate(MTLWB.MTService.TranslationServiceLoc.TranslateRequest request);
        
        // CODEGEN: Generating message contract since element name Request from namespace http://schemas.microsoft.com/MSNSearch/2005/09/fex is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/MSNSearch/2005/09/fex/GetTranslationSystems", ReplyAction="http://schemas.microsoft.com/MSNSearch/2005/09/fex/GetTranslationSystemsResponse")]
        MTLWB.MTService.TranslationServiceLoc.GetTranslationSystemsResponse GetTranslationSystems(MTLWB.MTService.TranslationServiceLoc.GetTranslationSystemsRequest request);
        
        // CODEGEN: Generating message contract since element name Request from namespace http://schemas.microsoft.com/MSNSearch/2005/09/fex is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/MSNSearch/2005/09/fex/GetErrorString", ReplyAction="http://schemas.microsoft.com/MSNSearch/2005/09/fex/GetErrorStringResponse")]
        MTLWB.MTService.TranslationServiceLoc.GetErrorStringResponse GetErrorString(MTLWB.MTService.TranslationServiceLoc.GetErrorStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class TranslateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Translate", Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex", Order=0)]
        public MTLWB.MTService.TranslationServiceLoc.TranslateRequestBody Body;
        
        public TranslateRequest() {
        }
        
        public TranslateRequest(MTLWB.MTService.TranslationServiceLoc.TranslateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    internal partial class TranslateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MTLWB.MTService.TranslationServiceLoc.TranslationRequest Request;
        
        public TranslateRequestBody() {
        }
        
        public TranslateRequestBody(MTLWB.MTService.TranslationServiceLoc.TranslationRequest Request) {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class TranslateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TranslateResponse", Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex", Order=0)]
        public MTLWB.MTService.TranslationServiceLoc.TranslateResponseBody Body;
        
        public TranslateResponse() {
        }
        
        public TranslateResponse(MTLWB.MTService.TranslationServiceLoc.TranslateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    internal partial class TranslateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public MTLWB.MTService.TranslationServiceLoc.TranslationResponse TranslateResult;
        
        public TranslateResponseBody() {
        }
        
        public TranslateResponseBody(MTLWB.MTService.TranslationServiceLoc.TranslationResponse TranslateResult) {
            this.TranslateResult = TranslateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetTranslationSystemsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTranslationSystems", Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex", Order=0)]
        public MTLWB.MTService.TranslationServiceLoc.GetTranslationSystemsRequestBody Body;
        
        public GetTranslationSystemsRequest() {
        }
        
        public GetTranslationSystemsRequest(MTLWB.MTService.TranslationServiceLoc.GetTranslationSystemsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    internal partial class GetTranslationSystemsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MTLWB.MTService.TranslationServiceLoc.TranslationSystemRequest Request;
        
        public GetTranslationSystemsRequestBody() {
        }
        
        public GetTranslationSystemsRequestBody(MTLWB.MTService.TranslationServiceLoc.TranslationSystemRequest Request) {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetTranslationSystemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTranslationSystemsResponse", Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex", Order=0)]
        public MTLWB.MTService.TranslationServiceLoc.GetTranslationSystemsResponseBody Body;
        
        public GetTranslationSystemsResponse() {
        }
        
        public GetTranslationSystemsResponse(MTLWB.MTService.TranslationServiceLoc.GetTranslationSystemsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    internal partial class GetTranslationSystemsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MTLWB.MTService.TranslationServiceLoc.TranslationSystemResponse GetTranslationSystemsResult;
        
        public GetTranslationSystemsResponseBody() {
        }
        
        public GetTranslationSystemsResponseBody(MTLWB.MTService.TranslationServiceLoc.TranslationSystemResponse GetTranslationSystemsResult) {
            this.GetTranslationSystemsResult = GetTranslationSystemsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetErrorStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetErrorString", Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex", Order=0)]
        public MTLWB.MTService.TranslationServiceLoc.GetErrorStringRequestBody Body;
        
        public GetErrorStringRequest() {
        }
        
        public GetErrorStringRequest(MTLWB.MTService.TranslationServiceLoc.GetErrorStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    internal partial class GetErrorStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MTLWB.MTService.TranslationServiceLoc.ErrorRequest Request;
        
        public GetErrorStringRequestBody() {
        }
        
        public GetErrorStringRequestBody(MTLWB.MTService.TranslationServiceLoc.ErrorRequest Request) {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetErrorStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetErrorStringResponse", Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex", Order=0)]
        public MTLWB.MTService.TranslationServiceLoc.GetErrorStringResponseBody Body;
        
        public GetErrorStringResponse() {
        }
        
        public GetErrorStringResponse(MTLWB.MTService.TranslationServiceLoc.GetErrorStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    internal partial class GetErrorStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MTLWB.MTService.TranslationServiceLoc.ErrorResponse GetErrorStringResult;
        
        public GetErrorStringResponseBody() {
        }
        
        public GetErrorStringResponseBody(MTLWB.MTService.TranslationServiceLoc.ErrorResponse GetErrorStringResult) {
            this.GetErrorStringResult = GetErrorStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ITranslationServiceContractChannel : MTLWB.MTService.TranslationServiceLoc.ITranslationServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class TranslationServiceContractClient : System.ServiceModel.ClientBase<MTLWB.MTService.TranslationServiceLoc.ITranslationServiceContract>, MTLWB.MTService.TranslationServiceLoc.ITranslationServiceContract {
        
        public TranslationServiceContractClient() {
        }
        
        public TranslationServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TranslationServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslationServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslationServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MTLWB.MTService.TranslationServiceLoc.TranslateResponse MTLWB.MTService.TranslationServiceLoc.ITranslationServiceContract.Translate(MTLWB.MTService.TranslationServiceLoc.TranslateRequest request) {
            return base.Channel.Translate(request);
        }
        
        public MTLWB.MTService.TranslationServiceLoc.TranslationResponse Translate(MTLWB.MTService.TranslationServiceLoc.TranslationRequest Request) {
            MTLWB.MTService.TranslationServiceLoc.TranslateRequest inValue = new MTLWB.MTService.TranslationServiceLoc.TranslateRequest();
            inValue.Body = new MTLWB.MTService.TranslationServiceLoc.TranslateRequestBody();
            inValue.Body.Request = Request;
            MTLWB.MTService.TranslationServiceLoc.TranslateResponse retVal = ((MTLWB.MTService.TranslationServiceLoc.ITranslationServiceContract)(this)).Translate(inValue);
            return retVal.Body.TranslateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MTLWB.MTService.TranslationServiceLoc.GetTranslationSystemsResponse MTLWB.MTService.TranslationServiceLoc.ITranslationServiceContract.GetTranslationSystems(MTLWB.MTService.TranslationServiceLoc.GetTranslationSystemsRequest request) {
            return base.Channel.GetTranslationSystems(request);
        }
        
        public MTLWB.MTService.TranslationServiceLoc.TranslationSystemResponse GetTranslationSystems(MTLWB.MTService.TranslationServiceLoc.TranslationSystemRequest Request) {
            MTLWB.MTService.TranslationServiceLoc.GetTranslationSystemsRequest inValue = new MTLWB.MTService.TranslationServiceLoc.GetTranslationSystemsRequest();
            inValue.Body = new MTLWB.MTService.TranslationServiceLoc.GetTranslationSystemsRequestBody();
            inValue.Body.Request = Request;
            MTLWB.MTService.TranslationServiceLoc.GetTranslationSystemsResponse retVal = ((MTLWB.MTService.TranslationServiceLoc.ITranslationServiceContract)(this)).GetTranslationSystems(inValue);
            return retVal.Body.GetTranslationSystemsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MTLWB.MTService.TranslationServiceLoc.GetErrorStringResponse MTLWB.MTService.TranslationServiceLoc.ITranslationServiceContract.GetErrorString(MTLWB.MTService.TranslationServiceLoc.GetErrorStringRequest request) {
            return base.Channel.GetErrorString(request);
        }
        
        public MTLWB.MTService.TranslationServiceLoc.ErrorResponse GetErrorString(MTLWB.MTService.TranslationServiceLoc.ErrorRequest Request) {
            MTLWB.MTService.TranslationServiceLoc.GetErrorStringRequest inValue = new MTLWB.MTService.TranslationServiceLoc.GetErrorStringRequest();
            inValue.Body = new MTLWB.MTService.TranslationServiceLoc.GetErrorStringRequestBody();
            inValue.Body.Request = Request;
            MTLWB.MTService.TranslationServiceLoc.GetErrorStringResponse retVal = ((MTLWB.MTService.TranslationServiceLoc.ITranslationServiceContract)(this)).GetErrorString(inValue);
            return retVal.Body.GetErrorStringResult;
        }
    }
}
