//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationAssistant.DocumentTranslationInterface.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslationAssistant.DocumentTranslationInterface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Category ID: 的本地化字符串。
        /// </summary>
        public static string Account_category {
            get {
                return ResourceManager.GetString("Account_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string Account_clear {
            get {
                return ResourceManager.GetString("Account_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key: 的本地化字符串。
        /// </summary>
        public static string Account_key {
            get {
                return ResourceManager.GetString("Account_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Region: 的本地化字符串。
        /// </summary>
        public static string Account_region {
            get {
                return ResourceManager.GetString("Account_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Account_save {
            get {
                return ResourceManager.GetString("Account_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show experimental languages 的本地化字符串。
        /// </summary>
        public static string Account_ShowExperimental {
            get {
                return ResourceManager.GetString("Account_ShowExperimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please subscribe to Microsoft Translator Text API at 的本地化字符串。
        /// </summary>
        public static string Account_string1 {
            get {
                return ResourceManager.GetString("Account_string1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optionally you may enter a category identifier to use a customized machine translation system. Enter the category ID of a custom system you have built on 的本地化字符串。
        /// </summary>
        public static string Account_string10 {
            get {
                return ResourceManager.GetString("Account_string10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Build a customized machine translation system here. 的本地化字符串。
        /// </summary>
        public static string Account_string11 {
            get {
                return ResourceManager.GetString("Account_string11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 and copy the Key for your Translator Text API resource into the field below. 的本地化字符串。
        /// </summary>
        public static string Account_string2 {
            get {
                return ResourceManager.GetString("Account_string2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscribe to Microsoft Translator 的本地化字符串。
        /// </summary>
        public static string Account_string3 {
            get {
                return ResourceManager.GetString("Account_string3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account 的本地化字符串。
        /// </summary>
        public static string Account_title {
            get {
                return ResourceManager.GetString("Account_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appid: 的本地化字符串。
        /// </summary>
        public static string Advanced_appid {
            get {
                return ResourceManager.GetString("Advanced_appid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please obtain the Server Address and the Appid to enter from the translation service administrator for your organization. 的本地化字符串。
        /// </summary>
        public static string Advanced_string10 {
            get {
                return ResourceManager.GetString("Advanced_string10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Any settings made here will override entries that are present in the &quot;Account&quot; page. 的本地化字符串。
        /// </summary>
        public static string Advanced_string11 {
            get {
                return ResourceManager.GetString("Advanced_string11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Address: 的本地化字符串。
        /// </summary>
        public static string Advanced_string20 {
            get {
                return ResourceManager.GetString("Advanced_string20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use these Advanced Settings instead of &quot;Account&quot;. 的本地化字符串。
        /// </summary>
        public static string Advanced_string21 {
            get {
                return ResourceManager.GetString("Advanced_string21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Settings 的本地化字符串。
        /// </summary>
        public static string Advanced_title {
            get {
                return ResourceManager.GetString("Advanced_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color theme: 的本地化字符串。
        /// </summary>
        public static string Appearance_colortheme {
            get {
                return ResourceManager.GetString("Appearance_colortheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font size: 的本地化字符串。
        /// </summary>
        public static string Appearance_fontsize {
            get {
                return ResourceManager.GetString("Appearance_fontsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appearance 的本地化字符串。
        /// </summary>
        public static string Appearance_title {
            get {
                return ResourceManager.GetString("Appearance_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Azure Link Type: 的本地化字符串。
        /// </summary>
        public static string Azure_LinkType {
            get {
                return ResourceManager.GetString("Azure_LinkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Azure China 的本地化字符串。
        /// </summary>
        public static string AzureChina_text {
            get {
                return ResourceManager.GetString("AzureChina_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Azure Global 的本地化字符串。
        /// </summary>
        public static string AzureGlobal_text {
            get {
                return ResourceManager.GetString("AzureGlobal_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Azure Government 的本地化字符串。
        /// </summary>
        public static string AzureGov_text {
            get {
                return ResourceManager.GetString("AzureGov_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto-Detect 的本地化字符串。
        /// </summary>
        public static string Common_AutoDetect {
            get {
                return ResourceManager.GetString("Common_AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTML 的本地化字符串。
        /// </summary>
        public static string Common_HTML {
            get {
                return ResourceManager.GetString("Common_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 plain text 的本地化字符串。
        /// </summary>
        public static string Common_PlainText {
            get {
                return ResourceManager.GetString("Common_PlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready to translate. 的本地化字符串。
        /// </summary>
        public static string Common_Ready {
            get {
                return ResourceManager.GetString("Common_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the documents and languages to translate. 的本地化字符串。
        /// </summary>
        public static string Common_SelectDocuments {
            get {
                return ResourceManager.GetString("Common_SelectDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings saved. Ready to translate. 的本地化字符串。
        /// </summary>
        public static string Common_SettingsSaved {
            get {
                return ResourceManager.GetString("Common_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Started 的本地化字符串。
        /// </summary>
        public static string Common_Started {
            get {
                return ResourceManager.GetString("Common_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation completed successfully.
        ///The translated documents contain the language identifier 的本地化字符串。
        /// </summary>
        public static string Common_Statustext1 {
            get {
                return ResourceManager.GetString("Common_Statustext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 in the file name. 的本地化字符串。
        /// </summary>
        public static string Common_Statustext2 {
            get {
                return ResourceManager.GetString("Common_Statustext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supported Files 的本地化字符串。
        /// </summary>
        public static string Common_SupportedFiles {
            get {
                return ResourceManager.GetString("Common_SupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translating document: 的本地化字符串。
        /// </summary>
        public static string Common_TranslatingDocument {
            get {
                return ResourceManager.GetString("Common_TranslatingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use container: 的本地化字符串。
        /// </summary>
        public static string CustomEndpoint {
            get {
                return ResourceManager.GetString("CustomEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Document Translator 的本地化字符串。
        /// </summary>
        public static string DocumentTranslator_name {
            get {
                return ResourceManager.GetString("DocumentTranslator_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V2: Category is invalid.
        ///Please visit https://hub.microsofttranslator.com to determine a valid category ID, leave empty, or use one of the standard categories. 的本地化字符串。
        /// </summary>
        public static string Error_CategoryV2Invalid {
            get {
                return ResourceManager.GetString("Error_CategoryV2Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Category is invalid.
        ///Please visit https://portal.customtranslator.azure.ai to determine a valid category ID, leave empty, or use one of the standard categories. 的本地化字符串。
        /// </summary>
        public static string Error_CategoryV3Invalid {
            get {
                return ResourceManager.GetString("Error_CategoryV3Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key is invalid.
        ///Please visit the Azure Portal to obtain a subscription key for the Translator Text API. 的本地化字符串。
        /// </summary>
        public static string Error_KeyInvalid {
            get {
                return ResourceManager.GetString("Error_KeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to retrieve language list from Translator service. 的本地化字符串。
        /// </summary>
        public static string Error_LanguageList {
            get {
                return ResourceManager.GetString("Error_LanguageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please subscribe to Microsoft Translator text API and enter your subscription key in the Settings page. 的本地化字符串。
        /// </summary>
        public static string Error_PleaseSubscribe {
            get {
                return ResourceManager.GetString("Error_PleaseSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error while processing document: 的本地化字符串。
        /// </summary>
        public static string Error_ProcessingDocument {
            get {
                return ResourceManager.GetString("Error_ProcessingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translations by Microsoft® Translator 的本地化字符串。
        /// </summary>
        public static string Home_attribution {
            get {
                return ResourceManager.GetString("Home_attribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate Microsoft Office documents: Word | Excel | Powerpoint. 的本地化字符串。
        /// </summary>
        public static string Home_string10 {
            get {
                return ResourceManager.GetString("Home_string10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate PDF. Requires Office 2013 or later installed on this PC. PDFs will be saved as Word documents. 的本地化字符串。
        /// </summary>
        public static string Home_string11 {
            get {
                return ResourceManager.GetString("Home_string11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate HTML, Markdown, SRT caption files, and plain text (.txt file) in UTF-8 character encoding. 的本地化字符串。
        /// </summary>
        public static string Home_string12 {
            get {
                return ResourceManager.GetString("Home_string12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate from any Microsoft Translator source language to any target language. 的本地化字符串。
        /// </summary>
        public static string Home_string13 {
            get {
                return ResourceManager.GetString("Home_string13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uses your Translator Text API account, and any MT systems that have been customized using Custom Translator. 的本地化字符串。
        /// </summary>
        public static string Home_string14 {
            get {
                return ResourceManager.GetString("Home_string14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command line operation, wildcards and multiple languages at once using DocumentTranslatorCmd.exe. 的本地化字符串。
        /// </summary>
        public static string Home_string15 {
            get {
                return ResourceManager.GetString("Home_string15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Main_Home {
            get {
                return ResourceManager.GetString("Main_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate 的本地化字符串。
        /// </summary>
        public static string Main_ImmediateWindow {
            get {
                return ResourceManager.GetString("Main_ImmediateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Main_Settings {
            get {
                return ResourceManager.GetString("Main_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string Settings_About {
            get {
                return ResourceManager.GetString("Settings_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Window 的本地化字符串。
        /// </summary>
        public static string TestWindow_Title {
            get {
                return ResourceManager.GetString("TestWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required: Enter the key to your Azure Translator subscription. 的本地化字符串。
        /// </summary>
        public static string Tooltip_AccountKey {
            get {
                return ResourceManager.GetString("Tooltip_AccountKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returns the sentence boundaries of the input.  的本地化字符串。
        /// </summary>
        public static string Tooltip_BreakSentences {
            get {
                return ResourceManager.GetString("Tooltip_BreakSentences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optional: Enter the category ID of the custom system you want to use.  的本地化字符串。
        /// </summary>
        public static string Tooltip_Category {
            get {
                return ResourceManager.GetString("Tooltip_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter the Url to the endpoint where you are hosting the Translator container. 的本地化字符串。
        /// </summary>
        public static string Tooltip_CustomUrl {
            get {
                return ResourceManager.GetString("Tooltip_CustomUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check this only if you have a container install of Translator (uncommon) 的本地化字符串。
        /// </summary>
        public static string Tooltip_CustomUrlCheckbox {
            get {
                return ResourceManager.GetString("Tooltip_CustomUrlCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returns a JSON array with the result of the Detect function call. 的本地化字符串。
        /// </summary>
        public static string Tooltip_Detect {
            get {
                return ResourceManager.GetString("Tooltip_Detect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return a dictionary entry for this item 的本地化字符串。
        /// </summary>
        public static string Tooltip_Dictionary {
            get {
                return ResourceManager.GetString("Tooltip_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required: Enter the region of your Azure Translator location. 的本地化字符串。
        /// </summary>
        public static string Tooltip_Region {
            get {
                return ResourceManager.GetString("Tooltip_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show the experimental languages. Not recommended for production use. 的本地化字符串。
        /// </summary>
        public static string Tooltip_ShowExperimental {
            get {
                return ResourceManager.GetString("Tooltip_ShowExperimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returns the translation of the input to the specified language. 的本地化字符串。
        /// </summary>
        public static string Tooltip_Translate {
            get {
                return ResourceManager.GetString("Tooltip_Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returns a translation from all of the Microsoft Translator languages to the selected language. Useful only for short strings. 的本地化字符串。
        /// </summary>
        public static string Tooltip_TranslateFromAll {
            get {
                return ResourceManager.GetString("Tooltip_TranslateFromAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returns a translation to all of the Microsoft Translator languages. Useful only for short strings. 的本地化字符串。
        /// </summary>
        public static string Tooltip_TranslateToAll {
            get {
                return ResourceManager.GetString("Tooltip_TranslateToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check if your account key is for Azure Government (azure.us). 的本地化字符串。
        /// </summary>
        public static string Tooltip_UseAzureGovernment {
            get {
                return ResourceManager.GetString("Tooltip_UseAzureGovernment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Break Sentences 的本地化字符串。
        /// </summary>
        public static string Translate_BreakSentences {
            get {
                return ResourceManager.GetString("Translate_BreakSentences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string Translate_Browse {
            get {
                return ResourceManager.GetString("Translate_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect 的本地化字符串。
        /// </summary>
        public static string Translate_Detect {
            get {
                return ResourceManager.GetString("Translate_Detect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dictionary 的本地化字符串。
        /// </summary>
        public static string Translate_Dictionary {
            get {
                return ResourceManager.GetString("Translate_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Documents 的本地化字符串。
        /// </summary>
        public static string Translate_Documents {
            get {
                return ResourceManager.GetString("Translate_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate from all 的本地化字符串。
        /// </summary>
        public static string Translate_FromAll {
            get {
                return ResourceManager.GetString("Translate_FromAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From Language 的本地化字符串。
        /// </summary>
        public static string Translate_FromLanguage {
            get {
                return ResourceManager.GetString("Translate_FromLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate 的本地化字符串。
        /// </summary>
        public static string Translate_Go {
            get {
                return ResourceManager.GetString("Translate_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore hidden content 的本地化字符串。
        /// </summary>
        public static string Translate_Hidden {
            get {
                return ResourceManager.GetString("Translate_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check to skip the following content:
        ///Word documents: hidden text 的本地化字符串。
        /// </summary>
        public static string Translate_HiddenTooltip {
            get {
                return ResourceManager.GetString("Translate_HiddenTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input: 的本地化字符串。
        /// </summary>
        public static string Translate_Input {
            get {
                return ResourceManager.GetString("Translate_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid credentials.
        ///Please visit the Settings page first to enter your Microsoft Translator credentials. 的本地化字符串。
        /// </summary>
        public static string Translate_invalidcredentials {
            get {
                return ResourceManager.GetString("Translate_invalidcredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content Type 的本地化字符串。
        /// </summary>
        public static string Translate_Mode {
            get {
                return ResourceManager.GetString("Translate_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result: 的本地化字符串。
        /// </summary>
        public static string Translate_Result {
            get {
                return ResourceManager.GetString("Translate_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of sentences: 的本地化字符串。
        /// </summary>
        public static string Translate_SentNum {
            get {
                return ResourceManager.GetString("Translate_SentNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate Documents 的本地化字符串。
        /// </summary>
        public static string Translate_title {
            get {
                return ResourceManager.GetString("Translate_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate to all 的本地化字符串。
        /// </summary>
        public static string Translate_ToAll {
            get {
                return ResourceManager.GetString("Translate_ToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To Language 的本地化字符串。
        /// </summary>
        public static string Translate_ToLanguage {
            get {
                return ResourceManager.GetString("Translate_ToLanguage", resourceCulture);
            }
        }
    }
}
