//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationAssistant.DocumentTranslationInterface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslationAssistant.DocumentTranslationInterface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category ID:.
        /// </summary>
        public static string Account_category {
            get {
                return ResourceManager.GetString("Account_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Account_clear {
            get {
                return ResourceManager.GetString("Account_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key:.
        /// </summary>
        public static string Account_key {
            get {
                return ResourceManager.GetString("Account_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Account_save {
            get {
                return ResourceManager.GetString("Account_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show experimental languages.
        /// </summary>
        public static string Account_ShowExperimental {
            get {
                return ResourceManager.GetString("Account_ShowExperimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please subscribe to Microsoft Translator Text API at.
        /// </summary>
        public static string Account_string1 {
            get {
                return ResourceManager.GetString("Account_string1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionally you may enter a category identifier to use a customized machine translation system. Enter the category ID of a custom system you have built on.
        /// </summary>
        public static string Account_string10 {
            get {
                return ResourceManager.GetString("Account_string10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build a customized machine translation system here..
        /// </summary>
        public static string Account_string11 {
            get {
                return ResourceManager.GetString("Account_string11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and copy the Key for your Translator Text API resource into the field below..
        /// </summary>
        public static string Account_string2 {
            get {
                return ResourceManager.GetString("Account_string2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to Microsoft Translator.
        /// </summary>
        public static string Account_string3 {
            get {
                return ResourceManager.GetString("Account_string3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account_title {
            get {
                return ResourceManager.GetString("Account_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appid:.
        /// </summary>
        public static string Advanced_appid {
            get {
                return ResourceManager.GetString("Advanced_appid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please obtain the Server Address and the Appid to enter from the translation service administrator for your organization..
        /// </summary>
        public static string Advanced_string10 {
            get {
                return ResourceManager.GetString("Advanced_string10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any settings made here will override entries that are present in the &quot;Account&quot; page..
        /// </summary>
        public static string Advanced_string11 {
            get {
                return ResourceManager.GetString("Advanced_string11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Address:.
        /// </summary>
        public static string Advanced_string20 {
            get {
                return ResourceManager.GetString("Advanced_string20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use these Advanced Settings instead of &quot;Account&quot;..
        /// </summary>
        public static string Advanced_string21 {
            get {
                return ResourceManager.GetString("Advanced_string21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        public static string Advanced_title {
            get {
                return ResourceManager.GetString("Advanced_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color theme:.
        /// </summary>
        public static string Appearance_colortheme {
            get {
                return ResourceManager.GetString("Appearance_colortheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size:.
        /// </summary>
        public static string Appearance_fontsize {
            get {
                return ResourceManager.GetString("Appearance_fontsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance_title {
            get {
                return ResourceManager.GetString("Appearance_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Cloud to use:.
        /// </summary>
        public static string AzureCloud_text {
            get {
                return ResourceManager.GetString("AzureCloud_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Region:.
        /// </summary>
        public static string AzureRegion_text {
            get {
                return ResourceManager.GetString("AzureRegion_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Detect.
        /// </summary>
        public static string Common_AutoDetect {
            get {
                return ResourceManager.GetString("Common_AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        public static string Common_HTML {
            get {
                return ResourceManager.GetString("Common_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plain text.
        /// </summary>
        public static string Common_PlainText {
            get {
                return ResourceManager.GetString("Common_PlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to translate..
        /// </summary>
        public static string Common_Ready {
            get {
                return ResourceManager.GetString("Common_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the documents and languages to translate..
        /// </summary>
        public static string Common_SelectDocuments {
            get {
                return ResourceManager.GetString("Common_SelectDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved. Ready to translate..
        /// </summary>
        public static string Common_SettingsSaved {
            get {
                return ResourceManager.GetString("Common_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string Common_Started {
            get {
                return ResourceManager.GetString("Common_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation completed successfully.
        ///The translated documents contain the language identifier.
        /// </summary>
        public static string Common_Statustext1 {
            get {
                return ResourceManager.GetString("Common_Statustext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in the file name..
        /// </summary>
        public static string Common_Statustext2 {
            get {
                return ResourceManager.GetString("Common_Statustext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Files.
        /// </summary>
        public static string Common_SupportedFiles {
            get {
                return ResourceManager.GetString("Common_SupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translating document:.
        /// </summary>
        public static string Common_TranslatingDocument {
            get {
                return ResourceManager.GetString("Common_TranslatingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use container:.
        /// </summary>
        public static string CustomEndpoint {
            get {
                return ResourceManager.GetString("CustomEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Translator.
        /// </summary>
        public static string DocumentTranslator_name {
            get {
                return ResourceManager.GetString("DocumentTranslator_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2: Category is invalid.
        ///Please visit https://hub.microsofttranslator.com to determine a valid category ID, leave empty, or use one of the standard categories..
        /// </summary>
        public static string Error_CategoryV2Invalid {
            get {
                return ResourceManager.GetString("Error_CategoryV2Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is invalid.
        ///Please visit https://portal.customtranslator.azure.ai to determine a valid category ID, leave empty, or use one of the standard categories..
        /// </summary>
        public static string Error_CategoryV3Invalid {
            get {
                return ResourceManager.GetString("Error_CategoryV3Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is invalid.
        ///Please visit the Azure Portal to obtain a subscription key for the Translator Text API..
        /// </summary>
        public static string Error_KeyInvalid {
            get {
                return ResourceManager.GetString("Error_KeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve language list from Translator service..
        /// </summary>
        public static string Error_LanguageList {
            get {
                return ResourceManager.GetString("Error_LanguageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please subscribe to Microsoft Translator text API and enter your subscription key in the Settings page..
        /// </summary>
        public static string Error_PleaseSubscribe {
            get {
                return ResourceManager.GetString("Error_PleaseSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while processing document:.
        /// </summary>
        public static string Error_ProcessingDocument {
            get {
                return ResourceManager.GetString("Error_ProcessingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations by Microsoft® Translator.
        /// </summary>
        public static string Home_attribution {
            get {
                return ResourceManager.GetString("Home_attribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate Microsoft Office documents: Word | Excel | Powerpoint..
        /// </summary>
        public static string Home_string10 {
            get {
                return ResourceManager.GetString("Home_string10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate PDF. Requires Office 2013 or later installed on this PC. PDFs will be saved as Word documents..
        /// </summary>
        public static string Home_string11 {
            get {
                return ResourceManager.GetString("Home_string11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate HTML, Markdown, SRT caption files, and plain text (.txt file) in UTF-8 character encoding..
        /// </summary>
        public static string Home_string12 {
            get {
                return ResourceManager.GetString("Home_string12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate from any Microsoft Translator source language to any target language..
        /// </summary>
        public static string Home_string13 {
            get {
                return ResourceManager.GetString("Home_string13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses your Translator Text API account, and any MT systems that have been customized using Custom Translator..
        /// </summary>
        public static string Home_string14 {
            get {
                return ResourceManager.GetString("Home_string14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line operation, wildcards and multiple languages at once using DocumentTranslatorCmd.exe..
        /// </summary>
        public static string Home_string15 {
            get {
                return ResourceManager.GetString("Home_string15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Main_Home {
            get {
                return ResourceManager.GetString("Main_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string Main_ImmediateWindow {
            get {
                return ResourceManager.GetString("Main_ImmediateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Main_Settings {
            get {
                return ResourceManager.GetString("Main_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Settings_About {
            get {
                return ResourceManager.GetString("Settings_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Window.
        /// </summary>
        public static string TestWindow_Title {
            get {
                return ResourceManager.GetString("TestWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required: Enter the key to your Azure Translator subscription..
        /// </summary>
        public static string Tooltip_AccountKey {
            get {
                return ResourceManager.GetString("Tooltip_AccountKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which Azure cloud to use. China and US government cloud require a key in that region..
        /// </summary>
        public static string Tooltip_AzureCloud {
            get {
                return ResourceManager.GetString("Tooltip_AzureCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which Azure region is your Azure resource in?.
        /// </summary>
        public static string Tooltip_AzureRegion {
            get {
                return ResourceManager.GetString("Tooltip_AzureRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the sentence boundaries of the input. .
        /// </summary>
        public static string Tooltip_BreakSentences {
            get {
                return ResourceManager.GetString("Tooltip_BreakSentences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional: Enter the category ID of the custom system you want to use. .
        /// </summary>
        public static string Tooltip_Category {
            get {
                return ResourceManager.GetString("Tooltip_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Url to the endpoint where you are hosting the Translator container..
        /// </summary>
        public static string Tooltip_CustomUrl {
            get {
                return ResourceManager.GetString("Tooltip_CustomUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this only if you have a container install of Translator (uncommon).
        /// </summary>
        public static string Tooltip_CustomUrlCheckbox {
            get {
                return ResourceManager.GetString("Tooltip_CustomUrlCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns a JSON array with the result of the Detect function call..
        /// </summary>
        public static string Tooltip_Detect {
            get {
                return ResourceManager.GetString("Tooltip_Detect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return a dictionary entry for this item.
        /// </summary>
        public static string Tooltip_Dictionary {
            get {
                return ResourceManager.GetString("Tooltip_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all languages in all languages.
        /// </summary>
        public static string Tooltip_ListAllLanguages {
            get {
                return ResourceManager.GetString("Tooltip_ListAllLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the experimental languages. Not recommended for production use..
        /// </summary>
        public static string Tooltip_ShowExperimental {
            get {
                return ResourceManager.GetString("Tooltip_ShowExperimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the translation of the input to the specified language..
        /// </summary>
        public static string Tooltip_Translate {
            get {
                return ResourceManager.GetString("Tooltip_Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns a translation from all of the Microsoft Translator languages to the selected language. Useful only for short strings..
        /// </summary>
        public static string Tooltip_TranslateFromAll {
            get {
                return ResourceManager.GetString("Tooltip_TranslateFromAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns a translation to all of the Microsoft Translator languages. Useful only for short strings..
        /// </summary>
        public static string Tooltip_TranslateToAll {
            get {
                return ResourceManager.GetString("Tooltip_TranslateToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Sentences.
        /// </summary>
        public static string Translate_BreakSentences {
            get {
                return ResourceManager.GetString("Translate_BreakSentences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Translate_Browse {
            get {
                return ResourceManager.GetString("Translate_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect.
        /// </summary>
        public static string Translate_Detect {
            get {
                return ResourceManager.GetString("Translate_Detect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary.
        /// </summary>
        public static string Translate_Dictionary {
            get {
                return ResourceManager.GetString("Translate_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Translate_Documents {
            get {
                return ResourceManager.GetString("Translate_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate from all.
        /// </summary>
        public static string Translate_FromAll {
            get {
                return ResourceManager.GetString("Translate_FromAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Language.
        /// </summary>
        public static string Translate_FromLanguage {
            get {
                return ResourceManager.GetString("Translate_FromLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string Translate_Go {
            get {
                return ResourceManager.GetString("Translate_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore hidden content.
        /// </summary>
        public static string Translate_Hidden {
            get {
                return ResourceManager.GetString("Translate_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to skip the following content:
        ///Word documents: hidden text.
        /// </summary>
        public static string Translate_HiddenTooltip {
            get {
                return ResourceManager.GetString("Translate_HiddenTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input:.
        /// </summary>
        public static string Translate_Input {
            get {
                return ResourceManager.GetString("Translate_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        ///Please visit the Settings page first to enter your Microsoft Translator credentials..
        /// </summary>
        public static string Translate_invalidcredentials {
            get {
                return ResourceManager.GetString("Translate_invalidcredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all languages.
        /// </summary>
        public static string Translate_ListAllLanguages {
            get {
                return ResourceManager.GetString("Translate_ListAllLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Type.
        /// </summary>
        public static string Translate_Mode {
            get {
                return ResourceManager.GetString("Translate_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result:.
        /// </summary>
        public static string Translate_Result {
            get {
                return ResourceManager.GetString("Translate_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sentences:.
        /// </summary>
        public static string Translate_SentNum {
            get {
                return ResourceManager.GetString("Translate_SentNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate Documents.
        /// </summary>
        public static string Translate_title {
            get {
                return ResourceManager.GetString("Translate_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate to all.
        /// </summary>
        public static string Translate_ToAll {
            get {
                return ResourceManager.GetString("Translate_ToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Language.
        /// </summary>
        public static string Translate_ToLanguage {
            get {
                return ResourceManager.GetString("Translate_ToLanguage", resourceCulture);
            }
        }
    }
}
